/**
 * A small Web Audio voice for Chorus.
 *
 * The SDK's shared sound kit covers fixed UI cues; it is not a note player, so
 * the song itself is synthesised here. Nothing is fetched: every sample is
 * generated by oscillators, so the sandbox CSP is untouched.
 *
 * Timing is returned to the caller as plain milliseconds computed from the
 * composition alone. Visuals and echo scoring run off those numbers, so the game
 * keeps working identically when the player is muted or audio is unavailable.
 */
import type { Note, Phrase, Voice } from "./composition.js";

export type ScheduledPhrase = Readonly<{
  /** Note onsets in milliseconds from the start of playback. */
  onsets: readonly number[];
  /** Total length of the phrase in milliseconds. */
  duration: number;
}>;

export type ChorusSynth = Readonly<{
  unlock(): Promise<boolean>;
  available(): boolean;
  setMuted(muted: boolean): void;
  /** Schedule a phrase and return its timing, whether or not audio plays. */
  playPhrase(phrase: Phrase, voice: Voice, secondsPerBeat: number, layers?: number, delayMs?: number): ScheduledPhrase;
  /** Schedule several phrases back to back, returning each phrase's start offset. */
  playSequence(phrases: readonly Phrase[], voice: Voice, secondsPerBeat: number, layersFor: (phrase: Phrase) => number): Readonly<{ starts: readonly number[]; duration: number }>;
  stop(): void;
  dispose(): void;
}>;

const ATTACK = 0.012;
const MASTER_LEVEL = 0.22;
const MAX_LAYERS = 3;

export function createChorusSynth(): ChorusSynth {
  let context: AudioContext | null = null;
  let master: GainNode | null = null;
  let muted = false;
  let disposed = false;
  let unsupported = false;
  let live: { osc: OscillatorNode; gain: GainNode }[] = [];

  const applyLevel = () => { if (master && context) master.gain.setValueAtTime(muted ? 0 : MASTER_LEVEL, context.currentTime); };

  function sound(note: Note, at: number, seconds: number, voice: Voice, layers: number) {
    if (!context || !master || muted) return;
    const level = 1 / Math.sqrt(Math.max(1, layers));
    for (let layer = 0; layer < Math.min(layers, MAX_LAYERS); layer++) {
      // Extra copies of a phrase thicken it an octave up instead of getting louder.
      const frequency = note.frequency * (layer === 0 ? 1 : 2 ** layer);
      const gain = context.createGain();
      const filter = context.createBiquadFilter();
      filter.type = "lowpass";
      filter.frequency.setValueAtTime(voice.cutoff, at);
      const hold = Math.max(0.06, seconds * 0.9);
      const peak = (layer === 0 ? 0.9 : 0.35 / layer) * level;
      gain.gain.setValueAtTime(0.0001, at);
      gain.gain.exponentialRampToValueAtTime(Math.max(0.0002, peak), at + ATTACK);
      gain.gain.exponentialRampToValueAtTime(0.0001, at + hold + voice.release);
      filter.connect(gain);
      gain.connect(master);
      const detunes = voice.detune > 0 && layer === 0 ? [-voice.detune, voice.detune] : [0];
      for (const cents of detunes) {
        const osc = context.createOscillator();
        osc.type = voice.wave;
        osc.frequency.setValueAtTime(frequency, at);
        osc.detune.setValueAtTime(cents, at);
        osc.connect(filter);
        osc.start(at);
        osc.stop(at + hold + voice.release + 0.05);
        const entry = { osc, gain };
        live.push(entry);
        osc.onended = () => {
          live = live.filter(item => item !== entry);
          try { osc.disconnect(); gain.disconnect(); filter.disconnect(); } catch { /* already torn down */ }
        };
      }
    }
  }

  function scheduleNotes(notes: readonly Note[], voice: Voice, secondsPerBeat: number, layers: number, offsetSeconds: number) {
    const onsets: number[] = [];
    let cursor = 0;
    for (const note of notes) {
      onsets.push((offsetSeconds + cursor) * 1000);
      const seconds = note.beats * secondsPerBeat;
      if (context && master && !muted) sound(note, context.currentTime + offsetSeconds + cursor, seconds, voice, layers);
      cursor += seconds;
    }
    return { onsets, seconds: cursor };
  }

  return Object.freeze({
    available: () => Boolean(context) && !unsupported && !disposed,
    async unlock() {
      if (disposed || unsupported) return false;
      if (!context) {
        const Ctor = globalThis.AudioContext
          ?? (globalThis as typeof globalThis & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
        if (!Ctor) { unsupported = true; return false; }
        try {
          context = new Ctor();
          master = context.createGain();
          master.connect(context.destination);
          applyLevel();
        } catch { unsupported = true; context = null; master = null; return false; }
      }
      try { if (context.state === "suspended") await context.resume(); } catch { return false; }
      return context.state === "running";
    },
    setMuted(next) { muted = next; if (next) this.stop(); applyLevel(); },
    playPhrase(phrase, voice, secondsPerBeat, layers = 1, delayMs = 0) {
      const { onsets, seconds } = scheduleNotes(phrase.notes, voice, secondsPerBeat, layers, delayMs / 1000);
      return Object.freeze({ onsets: Object.freeze(onsets), duration: seconds * 1000 + delayMs + voice.release * 1000 });
    },
    playSequence(phrases, voice, secondsPerBeat, layersFor) {
      const starts: number[] = [];
      let cursor = 0;
      for (const phrase of phrases) {
        starts.push(cursor * 1000);
        const { seconds } = scheduleNotes(phrase.notes, voice, secondsPerBeat, layersFor(phrase), cursor);
        // A beat of air between phrases so the song breathes.
        cursor += seconds + secondsPerBeat;
      }
      return Object.freeze({ starts: Object.freeze(starts), duration: cursor * 1000 + voice.release * 1000 });
    },
    stop() {
      for (const { osc, gain } of live) {
        try { gain.gain.cancelScheduledValues(context?.currentTime ?? 0); osc.stop(); } catch { /* already stopped */ }
      }
      live = [];
    },
    dispose() {
      this.stop();
      disposed = true;
      try { void context?.close(); } catch { /* nothing to close */ }
      context = null; master = null;
    },
  });
}
